/* Automatically generated by version.sh, do not manually edit! */
#ifndef IJKVERSION_H
#define IJKVERSION_H
<<<<<<< HEAD
#define IJKPLAYER_VERSION "k0.8.8-1-gd0ee77f6"
=======
#define IJKPLAYER_VERSION "k0.8.8-1-g781593d7"
>>>>>>> fa5631c77c22cca069a6263b5bdbb77dcd1dbe4f
#endif /* IJKVERSION_H */
